### ISSUE TITLE
Auth Middleware could processing static files

### ISSUE THREAD

**Issue by PipocaZalas** [kevinisaac/wsgi-static-middleware#1]
Hi @kevinisaac I think that authmid, while analyze the request can give free pass to static files, what do you think about it? how do you handle the authentication and authorization?

**Comment by kevinisaac** [comment]
Hey @MackYoel! It just doesn't feel right for me for one middleware to do both authentication and serve static files.

I am using Beaker (https://github.com/bbangert/beaker) for authentication as of now. It is pretty good actually, supports persistent session storage and caching too.

**Comment by MackYoel** [comment]
Great @kevinisaac I use redis for authentication, but now I'll see Beaker. So your middleware is executed before that any middleware?
